restapp:
  build: .
  ports:
    - "8080:8080"
  environment:
    jdbc.username: restuser
    jdbc.password: vavRavugun
    jdbc.url: jdbc:mysql://restdb:3306/restmeasure
  links:
    - restdb

restdb:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: paujTaiwry
    MYSQL_USER: restuser
    MYSQL_PASSWORD: vavRavugun
    MYSQL_DATABASE: restmeasure
